title: Syndication
url: syndication.streamdata.io
philosophy: This is our project area for syndicating relevant content, data, and other
  resources to a variety of locations. To help us at Streamdata.io better spread information
  related to streaming, webhooks, and other event-driven technology, we've setup this
  portal, and project area for tracking on the relevant syndication destinations,
  as well as tools for helping track the most sensible approach to syndicating content
  across these locations.
syndications:
- name: Reddit
  ranking: 1
  description: Managing the Streamdatio conversation over at Reddit.
  url: https://www.reddit.com/
  image: http://syndication.streamdata.io/images/reddit-logo.jpeg
  profile: https://www.reddit.com/domain/streamdata.io/
  search: https://www.reddit.com/search?q=streamdata.io
  latest:
  - title: How to handle retry with the EventBus?
    url: https://streamdata.io/blog/vert-x-how-to-handle-retry-with-the-eventbus/
  - title: Vert.x and the async calls chain
    url: https://streamdata.io/blog/vert-x-and-the-async-calls-chain/
  - title: Vert.x and the async calls chain
    url: https://streamdata.io/blog/vert-x-and-the-async-calls-chain/
  - title: Streaming Multiple Github Account Activity Feeds
    url: https://streamdata.io/blog/streaming-multiple-github-activity-feeds-using-streamdataio/
  - title: Adding Real-Time Data to HTML5 Financial Charts
    url: https://streamdata.io/blog/how-to-take-chartiq-one-step-further-with-real-time-data/
- name: Hacker News
  ranking: 2
  description: Managing the Streamdatio conversation over at Hacker News.
  url: https://news.ycombinator.com/
  image: http://syndication.streamdata.io/images/hacker-news.jpg
  profile: https://news.ycombinator.com/user?id=StreamdataIO
  search: https://hn.algolia.com/?query=streamdata.io&sort=byPopularity&prefix=false&page=0&dateRange=all&type=story
  latest:
  - title: Super-simple real-time chat with restdb.io and streamdata.io
    url: https://restdb.io/blog/#!posts/57026178d768113700004116
  - title: Server-Sent Events explained with usecases
    url: http://streamdata.io/blog/server-sent-events/
  - title: How to Build a Hello World Plugin for Kong
    url: http://streamdata.io/blog/developing-an-helloworld-kong-plugin/
  - title: Text Analysis Machine Learning APIs
    url: https://streamdata.io/blog/text-analysis-machine-learning-apis/
- name: LinkedIn
  ranking: 3
  description: Some description
  url: https://news.ycombinator.com/
  image: http://syndication.streamdata.io/images/hacker-news.jpg
  profile: https://news.ycombinator.com/user?id=StreamdataIO
  search: https://hn.algolia.com/?query=streamdata.io&sort=byPopularity&prefix=false&page=0&dateRange=all&type=story
  latest:
  - title: Super-simple real-time chat with restdb.io and streamdata.io
    url: https://restdb.io/blog/#!posts/57026178d768113700004116
  - title: Server-Sent Events explained with usecases
    url: http://streamdata.io/blog/server-sent-events/
  - title: How to Build a Hello World Plugin for Kong
    url: http://streamdata.io/blog/developing-an-helloworld-kong-plugin/
  - title: Text Analysis Machine Learning APIs
    url: https://streamdata.io/blog/text-analysis-machine-learning-apis/
markdown: kramdown
exclude:
- .rvmrc
- .rbenv-version
- README.md
- Rakefile
- changelog.md
- .DS_Store
github_user: streamdata-projects
github_repo: syndications
github_branch: master
competition:
- organization_id: h0XcqyN0TsVIt7ImRbcLW9Yy1SZ9ui123RAjzpLsJLkcc117
  name: DZone
  description: DZone Software provides tools and processes to help customers accelerate
    productivity through agile learning and knowledge-centered collaboration. Our
    proprietary TeamHub platform powers scalable, secure solutions for world-class
    customers like IBM, Microsoft, GE, LinkedIn, Amazon, Facebook, SAP and many more.
    We offer both cloud-hosted and on-premise TeamHub solutions, and our platform
    is widely used for internal, employee-facing applications as well as external,
    customer-facing applications.
  url: https://dzone.com
  email: ""
  blog_url: ""
  blog_rss_url: http://feeds.dzone.com/home
  twitter_url: https://twitter.com/DZone
  github_url: ""
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: ""
  image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/dzone-logo.png
  image_width: "150"
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches: []
  latest_hacker_news_searches: []
  tags:
  - Tech News
  - SDIO Syndication
  - Profiled
  - Media
- organization_id: u3uvH1232116cq6r8UxtKIF5K9K123wmwI2DYgbBykQ116vyqso117
  name: Hacker News
  description: Hacker News is a social news website focusing on computer science and
    entrepreneurship. It is run by Paul Grahams investment fund and startup incubator,
    Y Combinator.
  url: http://seekingalpha.com/news-article/565537-bing-more-accurate-than-google-study-finds
  email: ""
  blog_url: ""
  blog_rss_url: ""
  twitter_url: ""
  github_url: Streamdata
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: ""
  image: ""
  image_width: ""
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches: []
  latest_hacker_news_searches:
  - hacker_news_id: "17143224"
    title: Show HN Feedback for our free Data Warehouse needed
    url: ""
    author: ""
    created_at: "2018-05-24"
    points: "2"
  - hacker_news_id: "16329450"
    title: Use Hazelcast Jet to Stream Data from an IMap to a Kafka Topic
    url: https://blog.hazelcast.com/use-hazelcast-jet-stream-data-imap-kafka-topic/
    author: ""
    created_at: "2018-02-07"
    points: "2"
  - hacker_news_id: "16133648"
    title: Stream data from Kafka to the browser
    url: http://www.landoop.com/blog/2017/12/redux-lenses-streaming/
    author: ""
    created_at: "2018-01-12"
    points: "2"
  - hacker_news_id: "15967566"
    title: Stream data from Kafka to the browser using React/Redux
    url: https://medium.com/@SebDragomir/connecting-to-kafka-using-redux-lenses-streaming-96a10bf12e11
    author: ""
    created_at: "2017-12-19"
    points: "1"
  - hacker_news_id: "15597250"
    title: StreamData Property-based testing and data generation for Elixir
    url: https://elixir-lang.org/blog/2017/10/31/stream-data-property-based-testing-and-data-generation-for-elixir/
    author: ""
    created_at: "2017-10-31"
    points: "5"
  - hacker_news_id: "11840314"
    title: "RCP 11 \u2013 Stream data type proposal for Redis"
    url: https://github.com/redis/redis-rcp/blob/master/RCP11.md
    author: ""
    created_at: "2016-06-05"
    points: "125"
  - hacker_news_id: "11425995"
    title: Show HN Super-simple real-time chat with restdb.io and streamdata.io
    url: https://restdb.io/blog/#!posts/57026178d768113700004116
    author: ""
    created_at: "2016-04-04"
    points: "3"
  - hacker_news_id: "11360572"
    title: Streamdata.io at the GDG DevFest Paris 2016
    url: http://streamdata.io/blog/streamdata-io-at-the-gdg-devfest-paris-2016/
    author: ""
    created_at: "2016-03-25"
    points: "1"
  - hacker_news_id: "10163040"
    title: Apache Flink platform for scalable batch and stream data processing
    url: https://flink.apache.org/
    author: ""
    created_at: "2015-09-02"
    points: "2"
  - hacker_news_id: "9108123"
    title: Putting Apache Kafka to Use A Guide to Building a Stream Data Platform
    url: http://blog.confluent.io/2015/02/25/stream-data-platform-1/
    author: ""
    created_at: "2015-02-25"
    points: "33"
  - hacker_news_id: "9110098"
    title: Putting Apache Kafka to use a guide to building a stream data platform
      (Part 2)
    url: http://blog.confluent.io/2015/02/25/stream-data-platform-1
    author: ""
    created_at: "2015-02-25"
    points: "6"
  - hacker_news_id: "8878196"
    title: Detecting Anomalies in Stream Data
    url: https://github.com/twitter/AnomalyDetection
    author: ""
    created_at: "2015-01-12"
    points: "1"
  - hacker_news_id: "7985400"
    title: Show HN Stream data into S3 bucket using the multipart upload API and Node.js
    url: https://github.com/nathanpeck/s3-upload-stream
    author: ""
    created_at: "2014-07-03"
    points: "8"
  - hacker_news_id: "2198235"
    title: Study Claims Bing more accurate than Google Search
    url: http://seekingalpha.com/news-article/565537-bing-more-accurate-than-google-study-finds
    author: ""
    created_at: "2011-02-09"
    points: "2"
  tags:
  - SDIO Syndication
  - Links
  - Curation
  - Bookmarks
- organization_id: rHGu2O43h116868L87FuwJNJ123CxZGrxnAdkewzPXgo6TQ117
  name: LinkedIn
  description: 500 million+ members | Manage your professional identity. Build and
    engage with your professional network. Access knowledge, insights and opportunities.
  url: http://linkedin.com
  email: ""
  blog_url: http://blog.linkedin.com
  blog_rss_url: ""
  twitter_url: https://twitter.com/LinkedIn
  github_url: https://github.com/linkedin
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: https://developer.linkedin.com
  image: http://kinlane-productions.s3.amazonaws.com/screen-capture-api/221-linkedin.jpg
  image_width: "150"
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches: []
  latest_hacker_news_searches: []
  tags:
  - Technology
  - Stack Network
  - Stack
  - Social Networks
  - Social Network
  - Social API
  - Social
  - SDIO Syndication
  - SaaS
  - Profiled
  - My API Stack
  - Mobile
  - internet
  - Indie EdTech Data Jam
  - API Service Provider
  - API Provider
- organization_id: ZfpwQzgwRK6ZbvcKC6EBlzI0e1165xo0J2EsHOy123CgW116M117
  name: Reddit
  description: Reddit is a community of millions of users engaging in the creation
    of content and the sharing of conversation across tens of thousands of topics.
  url: http://streamdata.io/blog/integrating-streamdata-io-with-node-js/
  email: ""
  blog_url: http://www.redditblog.com/
  blog_rss_url: http://www.redditblog.com/feeds/posts/default?alt=rss
  twitter_url: https://twitter.com/reddit
  github_url: Streamdata.io
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: http://www.reddit.com/dev/api
  image: http://kinlane-productions.s3.amazonaws.com/screen-capture-api/3516-reddit.jpg
  image_width: "150"
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches:
  - reddit_id: "8"
    title: Wikipedia:Articles for deletion/Streamdata.io
    url: https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Streamdata.io
    author: Wiki_AfD_Watch
    created_date: "2018-06-23"
    score: "1"
  - reddit_id: "80"
    title: '[ARTICLE] How Do You Rank A Good Or Bad API?'
    url: https://www.reddit.com/r/api/comments/80evpc/article_how_do_you_rank_a_good_or_bad_api/
    author: wtf_irl
    created_date: "2018-02-26"
    score: "1"
  - reddit_id: "6"
    title: Streaming data from APIs with Vue.js and Streamdata.io
    url: https://streamdata.io/blog/streamdataio-vue-js-sample-realtime/
    author: wtf_irl
    created_date: "2017-08-17"
    score: "15"
  - reddit_id: "419"
    title: Need help deciding finalizing project description for resume
    url: https://www.reddit.com/r/cscareerquestions/comments/419mq8/need_help_deciding_finalizing_project_description/
    author: imgurceo
    created_date: "2016-01-16"
    score: "1"
  - reddit_id: "409"
    title: Hi, I just finished my first project and I need help describing it on my
      resume
    url: https://www.reddit.com/r/cscareerquestions/comments/409arz/hi_i_just_finished_my_first_project_and_i_need/
    author: imgurceo
    created_date: "2016-01-10"
    score: "3"
  - reddit_id: "3"
    title: Integrating Streamdata.io with node.js
    url: http://streamdata.io/blog/integrating-streamdata-io-with-node-js/
    author: jstuartmill
    created_date: "2015-10-23"
    score: "3"
  latest_hacker_news_searches: []
  tags:
  - Technology
  - Stack Network
  - Stack
  - Social
  - Social
  - SDIO Syndication
  - My API Stack
  - Mobile
  - Media
  - Links
  - internet
