title: Syndication
url: syndication.streamdata.io
philosophy: This is our project area for syndicating relevant content, data, and other
  resources to a variety of locations. To help us at Streamdata.io better spread information
  related to streaming, webhooks, and other event-driven technology, we've setup this
  portal, and project area for tracking on the relevant syndication destinations,
  as well as tools for helping track the most sensible approach to syndicating content
  across these locations.
syndications:
- organization_id: ""
  name: DZone
  description: DZone Software provides tools and processes to help customers accelerate
    productivity through agile learning and knowledge-centered collaboration.&nbsp;
  url: http://www.dzone.com
  email: ""
  blog_url: ""
  blog_rss_url: http://feeds.dzone.com/home
  twitter_url: https://twitter.com/DZone
  github_url: ""
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: ""
  image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/dzone-logo.png
  image_width: "150"
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches: []
  latest_hacker_news_searches: []
  tags:
  - Tech News
  - SDIO Syndication
  - Profiles
  - Media
- organization_id: ""
  name: Hacker News
  description: Hacker News is a social news website focusing on computer science and
    entrepreneurship. It is run by Paul Grahams investment fund and startup incubator,
    Y Combinator.
  url: https://news.ycombinator.com/
  email: ""
  blog_url: ""
  blog_rss_url: ""
  twitter_url: https://twitter.com/newsycombinator
  github_url: Streamdata
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: https://github.com/HackerNews/API
  image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/hn-246x0w.jpg
  image_width: "150"
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches: []
  latest_hacker_news_searches:
  - hacker_news_id: "17143224"
    title: Show HN Feedback for our free Data Warehouse needed
    url: ""
    created_at: "2018-05-24"
    points: "2"
  - hacker_news_id: "16329450"
    title: Use Hazelcast Jet to Stream Data from an IMap to a Kafka Topic
    url: https://blog.hazelcast.com/use-hazelcast-jet-stream-data-imap-kafka-topic/
    created_at: "2018-02-07"
    points: "2"
  - hacker_news_id: "16133648"
    title: Stream data from Kafka to the browser
    url: http://www.landoop.com/blog/2017/12/redux-lenses-streaming/
    created_at: "2018-01-12"
    points: "2"
  - hacker_news_id: "15967566"
    title: Stream data from Kafka to the browser using React/Redux
    url: https://medium.com/@SebDragomir/connecting-to-kafka-using-redux-lenses-streaming-96a10bf12e11
    created_at: "2017-12-19"
    points: "1"
  - hacker_news_id: "15597250"
    title: StreamData Property-based testing and data generation for Elixir
    url: https://elixir-lang.org/blog/2017/10/31/stream-data-property-based-testing-and-data-generation-for-elixir/
    created_at: "2017-10-31"
    points: "5"
  - hacker_news_id: "11840314"
    title: "RCP 11 \u2013 Stream data type proposal for Redis"
    url: https://github.com/redis/redis-rcp/blob/master/RCP11.md
    created_at: "2016-06-05"
    points: "125"
  - hacker_news_id: "11425995"
    title: Show HN Super-simple real-time chat with restdb.io and streamdata.io
    url: https://restdb.io/blog/#!posts/57026178d768113700004116
    created_at: "2016-04-04"
    points: "3"
  - hacker_news_id: "11360572"
    title: Streamdata.io at the GDG DevFest Paris 2016
    url: http://streamdata.io/blog/streamdata-io-at-the-gdg-devfest-paris-2016/
    created_at: "2016-03-25"
    points: "1"
  - hacker_news_id: "10163040"
    title: Apache Flink platform for scalable batch and stream data processing
    url: https://flink.apache.org/
    created_at: "2015-09-02"
    points: "2"
  - hacker_news_id: "9108123"
    title: Putting Apache Kafka to Use A Guide to Building a Stream Data Platform
    url: http://blog.confluent.io/2015/02/25/stream-data-platform-1/
    created_at: "2015-02-25"
    points: "33"
  - hacker_news_id: "9110098"
    title: Putting Apache Kafka to use a guide to building a stream data platform
      (Part 2)
    url: http://blog.confluent.io/2015/02/25/stream-data-platform-1
    created_at: "2015-02-25"
    points: "6"
  - hacker_news_id: "8878196"
    title: Detecting Anomalies in Stream Data
    url: https://github.com/twitter/AnomalyDetection
    created_at: "2015-01-12"
    points: "1"
  - hacker_news_id: "7985400"
    title: Show HN Stream data into S3 bucket using the multipart upload API and Node.js
    url: https://github.com/nathanpeck/s3-upload-stream
    created_at: "2014-07-03"
    points: "8"
  - hacker_news_id: "6014769"
    title: Why mobile web apps are slow
    url: http://sealedabstract.com/rants/why-mobile-web-apps-are-slow/
    created_at: "2013-07-09"
    points: "28"
  - hacker_news_id: "2559818"
    title: TermKit - a graphical terminal replacement
    url: http://acko.net/blog/on-termkit
    created_at: "2011-05-18"
    points: "53"
  - hacker_news_id: "2198235"
    title: Study Claims Bing more accurate than Google Search
    url: http://seekingalpha.com/news-article/565537-bing-more-accurate-than-google-study-finds
    created_at: "2011-02-09"
    points: "2"
  tags:
  - SDIO Syndication
  - Links
  - General Data
  - Curation
  - Bookmarks
- organization_id: ""
  name: LinkedIn
  description: DZone Software provides tools and processes to help customers accelerate
    productivity through agile learning and knowledge-centered collaboration.&nbsp;
  url: http://linkedin.com
  email: ""
  blog_url: http://blog.linkedin.com
  blog_rss_url: ""
  twitter_url: https://twitter.com/LinkedIn
  github_url: https://github.com/linkedin
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: https://developer.linkedin.com
  image: http://kinlane-productions.s3.amazonaws.com/screen-capture-api/221-linkedin.jpg
  image_width: "150"
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches: []
  latest_hacker_news_searches: []
  tags:
  - Technology
  - Streams
  - Stack Network
  - Stack
  - Social Networks
  - Social Networks
  - Social
  - Social
  - Service API
  - SDIO Syndication
  - SaaS
  - Relative StreamRank
  - Relative Data
  - Profiles
  - Pedestal
  - My API Stack
  - Mobile
  - internet
  - Indie EdTech Data Jam
  - General Data
  - API Service Provider
  - API Provider
- organization_id: ""
  name: Medium
  description: Medium is an online publishing platform founded by Twitter co-founder
    Evan Williams in August 2012. The platform has evolved into a hybrid of non-professional
    contributions and professional, paid contributions, an example of social journalism.
  url: https://medium.com/
  email: ""
  blog_url: ""
  blog_rss_url: ""
  twitter_url: https://twitter.com/Medium
  github_url: https://github.com/Medium
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: ""
  image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/medium-logo.png
  image_width: "150"
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches: []
  latest_hacker_news_searches: []
  tags:
  - Stack Network
  - SDIO Syndication
  - Relative Data
  - Profiles
  - Media
  - General Data
  - Communications
  - Blogging
  - API Service Provider
  - API Provider
- organization_id: ""
  name: Reddit
  description: Reddit is a community of millions of users engaging in the creation
    of content and the sharing of conversation across tens of thousands of topics.
  url: http://www.reddit.com
  email: ""
  blog_url: http://www.redditblog.com/
  blog_rss_url: http://www.redditblog.com/feeds/posts/default?alt=rss
  twitter_url: https://twitter.com/reddit
  github_url: Streamdata.io
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: http://www.reddit.com/dev/api
  image: http://kinlane-productions.s3.amazonaws.com/screen-capture-api/3516-reddit.jpg
  image_width: "150"
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches:
  - reddit_id: "8"
    title: Wikipedia:Articles for deletion/Streamdata.io
    url: https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Streamdata.io
    author: Wiki_AfD_Watch
    created_date: "2018-06-23"
    score: "1"
  - reddit_id: "80"
    title: '[ARTICLE] How Do You Rank A Good Or Bad API?'
    url: https://www.reddit.com/r/api/comments/80evpc/article_how_do_you_rank_a_good_or_bad_api/
    author: wtf_irl
    created_date: "2018-02-26"
    score: "1"
  - reddit_id: "6"
    title: Streaming data from APIs with Vue.js and Streamdata.io
    url: https://streamdata.io/blog/streamdataio-vue-js-sample-realtime/
    author: wtf_irl
    created_date: "2017-08-17"
    score: "15"
  - reddit_id: "419"
    title: Need help deciding finalizing project description for resume
    url: https://www.reddit.com/r/cscareerquestions/comments/419mq8/need_help_deciding_finalizing_project_description/
    author: imgurceo
    created_date: "2016-01-16"
    score: "1"
  - reddit_id: "409"
    title: Hi, I just finished my first project and I need help describing it on my
      resume
    url: https://www.reddit.com/r/cscareerquestions/comments/409arz/hi_i_just_finished_my_first_project_and_i_need/
    author: imgurceo
    created_date: "2016-01-10"
    score: "3"
  - reddit_id: "3"
    title: Integrating Streamdata.io with node.js
    url: http://streamdata.io/blog/integrating-streamdata-io-with-node-js/
    author: jstuartmill
    created_date: "2015-10-23"
    score: "3"
  latest_hacker_news_searches: []
  tags:
  - Technology
  - Streams
  - Stack Network
  - Stack
  - Social
  - Social
  - SDIO Syndication
  - Relative StreamRank
  - Pedestal
  - My API Stack
  - Mobile
  - Media
  - Links
  - internet
  - General Data
- organization_id: ""
  name: Sweetcode
  description: Creating a meaningful voice is our business with our customers, and
    our passion within our community. Sweetcode is a site owned and managed by Fixate
    IO. Its purpose is simple&mdash;to give techies a place to share what they know,
    and impact the market with higher-value blog content.&nbsp;
  url: https://sweetcode.io
  email: ""
  blog_url: ""
  blog_rss_url: https://sweetcode.io/feed/
  twitter_url: https://twitter.com/SweetCodeHQ
  github_url: ""
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: ""
  image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/Sweetcode-gray-shadow-300px.png
  image_width: "150"
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches: []
  latest_hacker_news_searches: []
  tags:
  - Tech Blog
  - SDIO Syndication
  - Mobile
  - Content
markdown: kramdown
exclude:
- .rvmrc
- .rbenv-version
- README.md
- Rakefile
- changelog.md
- .DS_Store
github_user: streamdata-projects
github_repo: syndications
github_branch: master
competition:
- organization_id: h0XcqyN0TsVIt7ImRbcLW9Yy1SZ9ui123RAjzpLsJLkcc117
  name: DZone
  description: DZone Software provides tools and processes to help customers accelerate
    productivity through agile learning and knowledge-centered collaboration. Our
    proprietary TeamHub platform powers scalable, secure solutions for world-class
    customers like IBM, Microsoft, GE, LinkedIn, Amazon, Facebook, SAP and many more.
    We offer both cloud-hosted and on-premise TeamHub solutions, and our platform
    is widely used for internal, employee-facing applications as well as external,
    customer-facing applications.
  url: https://dzone.com
  email: ""
  blog_url: ""
  blog_rss_url: http://feeds.dzone.com/home
  twitter_url: https://twitter.com/DZone
  github_url: ""
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: ""
  image: http://kinlane-productions.s3.amazonaws.com/api-evangelist-site/company/logos/dzone-logo.png
  image_width: "150"
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches: []
  latest_hacker_news_searches: []
  tags:
  - Tech News
  - SDIO Syndication
  - Profiled
  - Media
- organization_id: u3uvH1232116cq6r8UxtKIF5K9K123wmwI2DYgbBykQ116vyqso117
  name: Hacker News
  description: Hacker News is a social news website focusing on computer science and
    entrepreneurship. It is run by Paul Grahams investment fund and startup incubator,
    Y Combinator.
  url: http://seekingalpha.com/news-article/565537-bing-more-accurate-than-google-study-finds
  email: ""
  blog_url: ""
  blog_rss_url: ""
  twitter_url: ""
  github_url: Streamdata
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: ""
  image: ""
  image_width: ""
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches: []
  latest_hacker_news_searches:
  - hacker_news_id: "17143224"
    title: Show HN Feedback for our free Data Warehouse needed
    url: ""
    created_at: "2018-05-24"
    points: "2"
  - hacker_news_id: "16329450"
    title: Use Hazelcast Jet to Stream Data from an IMap to a Kafka Topic
    url: https://blog.hazelcast.com/use-hazelcast-jet-stream-data-imap-kafka-topic/
    created_at: "2018-02-07"
    points: "2"
  - hacker_news_id: "16133648"
    title: Stream data from Kafka to the browser
    url: http://www.landoop.com/blog/2017/12/redux-lenses-streaming/
    created_at: "2018-01-12"
    points: "2"
  - hacker_news_id: "15967566"
    title: Stream data from Kafka to the browser using React/Redux
    url: https://medium.com/@SebDragomir/connecting-to-kafka-using-redux-lenses-streaming-96a10bf12e11
    created_at: "2017-12-19"
    points: "1"
  - hacker_news_id: "15597250"
    title: StreamData Property-based testing and data generation for Elixir
    url: https://elixir-lang.org/blog/2017/10/31/stream-data-property-based-testing-and-data-generation-for-elixir/
    created_at: "2017-10-31"
    points: "5"
  - hacker_news_id: "11840314"
    title: "RCP 11 \u2013 Stream data type proposal for Redis"
    url: https://github.com/redis/redis-rcp/blob/master/RCP11.md
    created_at: "2016-06-05"
    points: "125"
  - hacker_news_id: "11425995"
    title: Show HN Super-simple real-time chat with restdb.io and streamdata.io
    url: https://restdb.io/blog/#!posts/57026178d768113700004116
    created_at: "2016-04-04"
    points: "3"
  - hacker_news_id: "11360572"
    title: Streamdata.io at the GDG DevFest Paris 2016
    url: http://streamdata.io/blog/streamdata-io-at-the-gdg-devfest-paris-2016/
    created_at: "2016-03-25"
    points: "1"
  - hacker_news_id: "10163040"
    title: Apache Flink platform for scalable batch and stream data processing
    url: https://flink.apache.org/
    created_at: "2015-09-02"
    points: "2"
  - hacker_news_id: "9108123"
    title: Putting Apache Kafka to Use A Guide to Building a Stream Data Platform
    url: http://blog.confluent.io/2015/02/25/stream-data-platform-1/
    created_at: "2015-02-25"
    points: "33"
  - hacker_news_id: "9110098"
    title: Putting Apache Kafka to use a guide to building a stream data platform
      (Part 2)
    url: http://blog.confluent.io/2015/02/25/stream-data-platform-1
    created_at: "2015-02-25"
    points: "6"
  - hacker_news_id: "8878196"
    title: Detecting Anomalies in Stream Data
    url: https://github.com/twitter/AnomalyDetection
    created_at: "2015-01-12"
    points: "1"
  - hacker_news_id: "7985400"
    title: Show HN Stream data into S3 bucket using the multipart upload API and Node.js
    url: https://github.com/nathanpeck/s3-upload-stream
    created_at: "2014-07-03"
    points: "8"
  - hacker_news_id: "2198235"
    title: Study Claims Bing more accurate than Google Search
    url: http://seekingalpha.com/news-article/565537-bing-more-accurate-than-google-study-finds
    created_at: "2011-02-09"
    points: "2"
  tags:
  - SDIO Syndication
  - Links
  - Curation
  - Bookmarks
- organization_id: rHGu2O43h116868L87FuwJNJ123CxZGrxnAdkewzPXgo6TQ117
  name: LinkedIn
  description: 500 million+ members | Manage your professional identity. Build and
    engage with your professional network. Access knowledge, insights and opportunities.
  url: http://linkedin.com
  email: ""
  blog_url: http://blog.linkedin.com
  blog_rss_url: ""
  twitter_url: https://twitter.com/LinkedIn
  github_url: https://github.com/linkedin
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: https://developer.linkedin.com
  image: http://kinlane-productions.s3.amazonaws.com/screen-capture-api/221-linkedin.jpg
  image_width: "150"
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches: []
  latest_hacker_news_searches: []
  tags:
  - Technology
  - Stack Network
  - Stack
  - Social Networks
  - Social Network
  - Social API
  - Social
  - SDIO Syndication
  - SaaS
  - Profiled
  - My API Stack
  - Mobile
  - internet
  - Indie EdTech Data Jam
  - API Service Provider
  - API Provider
- organization_id: ZfpwQzgwRK6ZbvcKC6EBlzI0e1165xo0J2EsHOy123CgW116M117
  name: Reddit
  description: Reddit is a community of millions of users engaging in the creation
    of content and the sharing of conversation across tens of thousands of topics.
  url: http://streamdata.io/blog/integrating-streamdata-io-with-node-js/
  email: ""
  blog_url: http://www.redditblog.com/
  blog_rss_url: http://www.redditblog.com/feeds/posts/default?alt=rss
  twitter_url: https://twitter.com/reddit
  github_url: Streamdata.io
  tag_url: ""
  tag_description: ""
  base_url: ""
  portal_url: http://www.reddit.com/dev/api
  image: http://kinlane-productions.s3.amazonaws.com/screen-capture-api/3516-reddit.jpg
  image_width: "150"
  latest_blog: []
  latest_tweets: []
  latest_github_activity: []
  latest_reddit_searches:
  - reddit_id: "8"
    title: Wikipedia:Articles for deletion/Streamdata.io
    url: https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Streamdata.io
    author: Wiki_AfD_Watch
    created_date: "2018-06-23"
    score: "1"
  - reddit_id: "80"
    title: '[ARTICLE] How Do You Rank A Good Or Bad API?'
    url: https://www.reddit.com/r/api/comments/80evpc/article_how_do_you_rank_a_good_or_bad_api/
    author: wtf_irl
    created_date: "2018-02-26"
    score: "1"
  - reddit_id: "6"
    title: Streaming data from APIs with Vue.js and Streamdata.io
    url: https://streamdata.io/blog/streamdataio-vue-js-sample-realtime/
    author: wtf_irl
    created_date: "2017-08-17"
    score: "15"
  - reddit_id: "419"
    title: Need help deciding finalizing project description for resume
    url: https://www.reddit.com/r/cscareerquestions/comments/419mq8/need_help_deciding_finalizing_project_description/
    author: imgurceo
    created_date: "2016-01-16"
    score: "1"
  - reddit_id: "409"
    title: Hi, I just finished my first project and I need help describing it on my
      resume
    url: https://www.reddit.com/r/cscareerquestions/comments/409arz/hi_i_just_finished_my_first_project_and_i_need/
    author: imgurceo
    created_date: "2016-01-10"
    score: "3"
  - reddit_id: "3"
    title: Integrating Streamdata.io with node.js
    url: http://streamdata.io/blog/integrating-streamdata-io-with-node-js/
    author: jstuartmill
    created_date: "2015-10-23"
    score: "3"
  latest_hacker_news_searches: []
  tags:
  - Technology
  - Stack Network
  - Stack
  - Social
  - Social
  - SDIO Syndication
  - My API Stack
  - Mobile
  - Media
  - Links
  - internet
curation:
  SDIO Syndication: []
